# Save new user 
POST http://localhost:3000/api/user/register 
content-type: application/json
apiKey: bbe44b27f2ea4464a198c929c1adc49e

{
"name": "sampled", "email": "enes@enes.com", "password": "123qwe"
}

###

# Login new user 
POST http://localhost:3000/api/user/login 
content-type: application/json
apiKey: bbe44b27f2ea4464a198c929c1adc49e

{
"email": "enes1@enes.com", "password": "123qwe"
}